# Generated by Django 3.2 on 2021-06-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=50)),
                ('service_desc', models.TextField()),
                ('image', models.FileField(null=True, upload_to='')),
                ('pub_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
