# Generated by Django 3.2 on 2021-06-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210620_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=500)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
