# Generated by Django 3.2 on 2021-06-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_customer_service_man_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(null=True, upload_to='customer/'),
        ),
        migrations.AlterField(
            model_name='service_man',
            name='image',
            field=models.ImageField(null=True, upload_to='service_man/'),
        ),
    ]
