# Generated by Django 3.2 on 2021-06-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210630_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_man',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
