# Generated by Django 3.2 on 2021-07-08 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookService',
        ),
    ]
